version: '3.8'

services:
  core:
    build:
      context: .
      dockerfile: Dockerfile
    working_dir: /usr/src/app/app/blackout-ua-core
    command: ["npm", "run", "start"]
    ports:
      - "3000:3000"
    depends_on:
      - redis
    networks:
      - app-network

  telegram:
    build:
      context: .
      dockerfile: Dockerfile
    working_dir: /usr/src/app/app/telegram
    command: ["npm", "run", "start:telegram"]
    ports:
      - "3001:3001"
    depends_on:
      - redis
    networks:
      - app-network

  redis:
    image: redis:alpine
    ports:
      - "6379:6379"
    networks:
      - app-network

networks:
  app-network:
    driver: bridge
